to: docx  # output format type.
output-file: result.docx  # output file name.
input-files:
- plosone_sample.md  # input file name(s).

from: markdown  # input file format.
reference-doc: plosone_template.docx  # style template word file.
filters:
- pantable  # For table import from .csv files.
- pandoc-mustache  # For variable substition purpose.
- pandoc-docx-pagebreakpy # For pagebreak
- pandoc-crossref

metadata:
    tableEqns: true
    titleDelim: "."
    tableTitle: "Table"
    tblPrefix: "Table"
    figureTitle: "Fig"
    figPrefix: 
        - "Fig"
        - "Figs"


